REPORTER = dot

test:
  @NODE_ENV=test ./node_modules/.bin/mocha \
    --compilers coffee:coffee-script/register \
    --reporter $(REPORTER) \
    --recursive \
    --colors

test-w: 
  @NODE_ENV=test ./node_modules/.bin/mocha \
    --compilers coffee:coffee-script/register \
    --reporter $(REPORTER) \
    --recursive \
    --colors \
    --growl \
    --watch

.PHONY: test test-w

# windows commands
# node_modules\.bin\mocha --compilers coffee:coffee-script/register --reporter dot --recursive --colors
# node_modules\.bin\mocha --compilers coffee:coffee-script/register --reporter dot --recursive --colors --watch